version: "3"

services:
  flask:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - "./src:/projects"
    tty: true
    environment:
      TZ: Asia/Tokyo
      FLASK_APP: run.py
      FLASK_ENV: development
    command: flask run --host 0.0.0.0 --port 5000
  mysql:
    image: mysql:5.7
    volumes:
      - "./database:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "flask"
      MYSQL_USER: "flask"
      MYSQL_PASSWORD: "flask"
    ports:
      - "3306:3306"
    depends_on:
      - flask
    restart: always
