version: "3"

services:
  flask:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - "./src:/app"
    tty: true
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - "flask-mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "flask"
      MYSQL_USER: "flask"
      MYSQL_PASSWORD: "flask"
    ports:
      - "3307:3306"
    depends_on:
      - flask
    restart: always
volumes:
  flask-mysql:
    driver: local
